const mongoose = require("mongoose");

const orderItemSchema = new mongoose.Schema(
  {
    name: {
      type: String,
      default: "",
    },

    sku: {
      type: String,
      default: "",
    },

    units: {
      type: Number,
      default: 1,
    },

    sellingPrice: {
      type: Number,
      default: 0,
    },

    discount: {
      type: Number,
      default: 0,
    },

    tax: {
      type: Number,
      default: 0,
    },

    hsn: {
      type: String,
      default: "",
    },
  },
  {
    _id: false,
  }
);


const OrderSchema = new mongoose.Schema(
  {
    // =====================================
    // Upload History
    // =====================================

    historyId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "UploadHistory",
      default: null,
      index: true,
    },

    uploadedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
      index: true,
    },

    companyID: {
      type: String,
      default: "",
    },

    externalOrderId: {
      type: String,
      required: true,
      trim: true,
    },


    // =====================================
    // Order Dates
    // =====================================

    orderDate: {
      type: Date,
      default: null,
    },


    // =====================================
    // Customer Details
    // =====================================

    consignorName: {
      type: String,
      default: "",
    },

    consignorPhone: {
      type: String,
      default: "",
      trim: true,
    },

    consigneeName: {
      type: String,
      default: "",
    },

    consigneeLastName: {
      type: String,
      default: "",
    },

    address: {
      type: String,
      default: "",
    },

    address2: {
      type: String,
      default: "",
    },

    destinationCity: {
      type: String,
      default: "",
    },

    destinationState: {
      type: String,
      default: "",
    },

    destinationPincode: {
      type: String,
      default: "",
    },

    destinationCountry: {
      type: String,
      default: "India",
    },

    consigneeEmail: {
      type: String,
      default: "",
    },

    billingPhone: {
      type: String,
      default: "",
    },

    billingAlternatePhone: {
      type: String,
      default: "",
    },


    // =====================================
    // Order Details
    // =====================================

    paymentMethod: {
      type: String,
      enum: ["COD", "Prepaid", "TO PAY"],
      default: "COD",
    },

    comment: {
      type: String,
      default: "",
    },


    orderItems: {
      type: [orderItemSchema],
      default: [],
    },


    invoiceNo: {
      type: String,
      default: "",
    },

    invoiceValueProvided: {
      type: Boolean,
      default: false,
    },

    invoiceAutoGenerated: {
      type: Boolean,
      default: false,
    },

    invoiceValue: {
      type: Number,
      default: 0,
    },


    subTotal: {
      type: Number,
      default: 0,
    },


    shippingCharges: {
      type: Number,
      default: 0,
    },


    giftwrapCharges: {
      type: Number,
      default: 0,
    },


    transactionCharges: {
      type: Number,
      default: 0,
    },


    totalDiscount: {
      type: Number,
      default: 0,
    },


    // =====================================
    // Package Details
    // =====================================

    weight: {
      type: Number,
      default: 0,
    },

    length: {
      type: Number,
      default: 0,
    },

    breadth: {
      type: Number,
      default: 0,
    },

    height: {
      type: Number,
      default: 0,
    },

    noOfBoxes: {
      type: Number,
      default: 1,
      min: 1,
    },

    actualWeight: {
      type: Number,
      default: 0,
    },

    volumetricWeight: {
      type: Number,
      default: 0,
    },

    chargeableWeight: {
      type: Number,
      default: 0,
    },

    category: {
      type: String,
      default: "Rest of India",
    },


    expectedHours: {
      type: Number,
      default: 144,
    },

    isReversePickup: {
      type: Boolean,
      default: false,
      index: true,
    },

    reversePickupId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "ReversePickup",
      default: null,
      index: true,
    },

  pickupPincode: {
      type: String,
      default: "",
      trim: true,
    },

    documents: {
      type: [
        {
          documentType: {
            type: String,
            enum: ["INVOICE", "EWAYBILL", "DELIVERY_CHALLAN", "OTHER"],
            default: "OTHER",
          },
          fileName: { type: String, default: "" },
          s3Key: { type: String, default: "" },
          s3Bucket: { type: String, default: "" },
          contentType: { type: String, default: "" },
          uploadedAt: { type: Date, default: Date.now },
        },
      ],
      default: [],
    },
  },
  {
    timestamps: true,
  }
);

OrderSchema.index({ externalOrderId: 1 }, { unique: true });
OrderSchema.index({ companyID: 1 });

module.exports = mongoose.model("Order", OrderSchema);