const hasItemPrice = (orderItems = []) =>
  (Array.isArray(orderItems) ? orderItems : []).some(
    (item) => Number(item.sellingPrice ?? item.selling_price ?? 0) > 0
  );

const resolveInvoiceGeneration = async ({
  invoiceNo,
  invoiceValue,
  orderItems = [],
  generateInvoiceNo,
}) => {
  const providedInvoiceNo = String(invoiceNo || "").trim();
  const hasProvidedInvoiceNo = Boolean(providedInvoiceNo);
  const hasProvidedInvoiceValue =
    invoiceValue !== undefined &&
    invoiceValue !== null &&
    String(invoiceValue).trim() !== "";
  const itemPriceProvided = hasItemPrice(orderItems);

  let resolvedInvoiceNo = providedInvoiceNo;
  if (!resolvedInvoiceNo && typeof generateInvoiceNo === "function") {
    resolvedInvoiceNo = await generateInvoiceNo();
  }

  return {
    providedInvoiceNo,
    hasProvidedInvoiceNo,
    hasProvidedInvoiceValue,
    itemPriceProvided,
    invoiceValueProvided: hasProvidedInvoiceValue,
    invoiceAutoGenerated:
      !hasProvidedInvoiceNo && !hasProvidedInvoiceValue && itemPriceProvided,
    resolvedInvoiceNo,
  };
};

module.exports = {
  hasItemPrice,
  resolveInvoiceGeneration,
};
