const mongoose = require("mongoose");

const reversePickupSchema = new mongoose.Schema(
  {
    requestId: {
      type: String,
      required: true,
      unique: true,
      index: true,
      trim: true,
    },
    companyID: {
      type: String,
      required: true,
      index: true,
      trim: true,
      uppercase: true,
    },
    requestedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
      index: true,
    },
    status: {
      type: String,
      enum: ["pending", "approved", "rejected", "awb_assigned", "failed"],
      default: "pending",
      index: true,
    },
    fromName: { type: String, required: true, trim: true },
    fromPhone: { type: String, required: true, trim: true },
    fromEmail: { type: String, default: "", trim: true },
    fromAddress: { type: String, required: true, trim: true },
    fromAddress2: { type: String, default: "", trim: true },
    fromCity: { type: String, required: true, trim: true },
    fromState: { type: String, required: true, trim: true },
    fromPincode: { type: String, required: true, trim: true },
    fromCountry: { type: String, default: "India", trim: true },
    toName: { type: String, required: true, trim: true },
    toPhone: { type: String, default: "", trim: true },
    toAddress: { type: String, required: true, trim: true },
    toCity: { type: String, required: true, trim: true },
    toState: { type: String, required: true, trim: true },
    toPincode: { type: String, required: true, trim: true },
    toCountry: { type: String, default: "India", trim: true },
    toLocationLabel: { type: String, default: "", trim: true },
    requestDate: { type: Date, default: () => new Date() },
    originalAwbNumber: { type: String, default: "", trim: true, index: true },
    pickupFor: { type: String, default: "", trim: true },
    modeType: {
      type: String,
      enum: ["Surface", "Air", "Prime"],
      default: "Surface",
    },
    itemDescription: { type: String, default: "", trim: true },
    paperWork: {
      type: String,
      enum: ["INVOICE", "EWAYBILL", "DELIVERY_CHALLAN", "OTHER"],
      default: "INVOICE",
    },
    invoiceValue: { type: Number, default: 0, min: 0 },
    supportingDocumentName: { type: String, default: "", trim: true },
    supportingDocumentPath: { type: String, default: "", trim: true },
    supportingDocumentS3Key: { type: String, default: "", trim: true },
    supportingDocumentS3Bucket: { type: String, default: "", trim: true },
    pieces: { type: Number, default: 1, min: 1 },
    weight: { type: Number, default: 0, min: 0 },
    length: { type: Number, default: 0, min: 0 },
    breadth: { type: Number, default: 0, min: 0 },
    height: { type: Number, default: 0, min: 0 },
    paymentMethod: {
      type: String,
      enum: ["COD", "Prepaid", "TO PAY"],
      default: "Prepaid",
    },
    preferredServiceType: {
      type: String,
      enum: ["surface", "air", "prime"],
      default: "surface",
    },
    pickupDate: { type: Date, required: true },
    requestedPickupDate: { type: Date, default: null },
    pickupTime: { type: String, default: "11:00", trim: true },
    notes: { type: String, default: "", trim: true },
    remarks: { type: String, default: "", trim: true },
    reviewedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      default: null,
    },
    reviewedAt: { type: Date, default: null },
    rejectionReason: { type: String, default: "", trim: true },
    failureReason: { type: String, default: "", trim: true },
    adminNotes: { type: String, default: "", trim: true },
    orderId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Order",
      default: null,
      index: true,
    },
    externalOrderId: { type: String, default: "", trim: true },
    awbNumber: { type: String, default: "", trim: true },
    courierName: { type: String, default: "", trim: true },
    assignedServiceType: {
      type: String,
      enum: ["surface", "air", "prime", null],
      default: null,
    },
  },
  { timestamps: true }
);

module.exports =
  mongoose.models.ReversePickup ||
  mongoose.model("ReversePickup", reversePickupSchema);
